In [ ]:
import pandas as pd

In [ ]:
a = pd.read_csv("SOCR-HeightWeight.csv")

In [ ]:
a.head()

   Index  Height(Inches)  Weight(Pounds)
0      1        65.78331        112.9925
1      2        71.51521        136.4873
2      3        69.39874        153.0269
3      4        68.21660        142.3354
4      5        67.78781        144.2971

In [ ]:
a.isnull().sum()

Index             0
Height(Inches)    0
Weight(Pounds)    0
dtype: int64

In [ ]:
a.isnull().any()

Index             False
Height(Inches)    False
Weight(Pounds)    False
dtype: bool

In [ ]:
x=a[["Height(Inches)"]]
x

       Height(Inches)
0            65.78331
1            71.51521
2            69.39874
3            68.21660
4            67.78781
...               ...
24995        69.50215
24996        64.54826
24997        64.69855
24998        67.52918
24999        68.87761

[25000 rows x 1 columns]

In [ ]:
y=a[["Weight(Pounds)"]]
y

       Weight(Pounds)
0            112.9925
1            136.4873
2            153.0269
3            142.3354
4            144.2971
...               ...
24995        118.0312
24996        120.1932
24997        118.2655
24998        132.2682
24999        124.8742

[25000 rows x 1 columns]

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [ ]:
print("X train")
x_train

X train

       Height(Inches)
18822        67.54277
933          67.66400
19417        68.08132
24237        68.63362
6908         68.76882
...               ...
17650        62.67320
22271        64.94584
10393        66.28166
19572        66.36876
14573        66.94490

[20000 rows x 1 columns]

In [ ]:
print("Y train")
y_train

Y train

       Weight(Pounds)
18822        121.0405
933          132.5153
19417        123.9994
24237        128.3377
6908         124.6462
...               ...
17650        121.4203
22271        104.0162
10393        132.7775
19572        122.2946
14573        129.0043

[20000 rows x 1 columns]

In [ ]:
print("X test")
x_test

X test

       Height(Inches)
22394        67.20582
17764        69.83556
20942        68.84252
24037        69.11634
2587         70.12002
...               ...
11608        65.08819
3274         66.99259
9210         69.67952
24544        66.45348
16643        65.39009

[5000 rows x 1 columns]

In [ ]:
print("Y test")
y_test

Y test

       Weight(Pounds)
22394        112.2300
17764        140.1353
20942        126.0857
24037        135.7018
2587         137.7196
...               ...
11608        129.1596
3274         122.1147
9210         138.7123
24544        122.2987
16643        131.0900

[5000 rows x 1 columns]

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
model=LinearRegression()

In [ ]:
model.fit(x_train,y_train)

LinearRegression()

In [ ]:
y_pred=model.predict(x_test)

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [ ]:
mean_absolute_error(y_test,y_pred)

8.1472583504863

In [ ]:
mean_squared_error(y_test,y_pred)

103.36878173284423

In [ ]:
r2_score(y_test,y_pred)

0.25288515695983604

In [ ]:
import joblib

In [ ]:
joblib.dump(model, "linear.pkl")

['linear.pkl']

In [ ]:
import joblib

In [ ]:
a=joblib.load("linear.pkl")

In [ ]:
a.predict([[100]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[225.52951861]])

# practice question

In [ ]:
import pandas as pd
df=pd.read_csv('data.csv')

In [ ]:
df.head(5)

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA

In [ ]:
x=df[['bedrooms','bathrooms','sqft_living','sqft_lot','floors','waterfront','view','condition','sqft_above','sqft_basement','yr_built','yr_renovated']]
y=df[['price']]

In [ ]:
df.isnull().any()

date             False
price            False
bedrooms         False
bathrooms        False
sqft_living      False
sqft_lot         False
floors           False
waterfront       False
view             False
condition        False
sqft_above       False
sqft_basement    False
yr_built         False
yr_renovated     False
street           False
city             False
statezip         False
country          False
dtype: bool

In [ ]:
df.isnull().sum()

date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
street           0
city             0
statezip         0
country          0
dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [ ]:
x_train

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated
3241,2.0,2.00,1180,9265,1.0,0,0,3,1180,0,1940,1996
3639,3.0,1.75,2200,14630,1.5,0,1,3,2200,0,1948,2003
514,4.0,3.25,3680,5759,2.0,0,0,3,2840,840,2003,0
1914,3.0,1.50,2080,5244,1.0,0,0,3,1190,890,1959,1989
3864,5.0,2.50,2160,7737,2.0,0,0,3,2160,0,1998,2006
...,...,...,...,...,...,...,...,...,...,...,...,...
1916,5.0,2.00,1750,10284,1.0,0,0,4,1750,0,1943,0
184,4.0,3.00,2450,10117,1.0,0,0,5,1580,870,1967,0
3845,3.0,1.75,2680,8625,1.0,0,0,5,1590,1090,1974,0
1561,4.0,1.75,1700,7800,1.0,0,0,5,1120,580,1981,0
148,5.0,3.50,4490,6000,2.0,0,0,3,3200,1290,2006,0

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
model=LinearRegression()

In [ ]:
model=LinearRegression()

In [ ]:
model.fit(x_train,y_train)

LinearRegression()

In [ ]:
y_pred=model.predict(x_test)

In [ ]:
model.predict(x_test)

array([[ 678848.45313675],
       [ 520924.35493471],
       [ 335972.06727849],
       [ 668853.19664025],
       [ 656688.60207645],
       [ 811193.85276393],
       [ 616180.89685433],
       [ 564504.74677632],
       [ 318265.79557509],
       [ 832682.38416789],
       [ 254027.43979721],
       [ 364102.54552816],
       [ 568280.38916824],
       [ 394228.37465261],
       [ 925826.75935203],
       [ 428483.42533208],
       [ 440010.62822582],
       [ 605462.34448792],
       [ 508836.42482421],
       [1142543.11046256],
       [ 496058.06684028],
       [ 280188.51443816],
       [ 821720.95287973],
       [ 447740.62371952],
       [ 897014.89261137],
       [1001573.87729459],
       [ 466650.37378274],
       [ 301035.36421237],
       [ 226108.71037025],
       [ 544151.43075204],
       [ 668307.41252847],
       [ 707858.59670159],
       [ 871419.44615248],
       [ 586789.2455105 ],
       [ 533608.45791966],
       [ 957897.73497155],
       [ 327524.49422193],
       [ 750325.30528292],
       [ 781441.84341866],
       [ 508996.5076825 ],
       [ 840778.39629291],
       [ 443968.75936682],
       [1389649.59219218],
       [ 961310.62914625],
       [ 529428.80213673],
       [ 590916.27603361],
       [ 426156.1207168 ],
       [ 573897.28822937],
       [ 650965.02990584],
       [ 576368.55894353],
       [ 701937.40238934],
       [ 436326.08419875],
       [ 326549.46807895],
       [ 398369.09685564],
       [ 389487.49565497],
       [ 185884.59094469],
       [ 449053.31094529],
       [ 826141.75987501],
       [ 433824.77539875],
       [ 580996.34340781],
       [ 569880.6617552 ],
       [ 727665.8922842 ],
       [ 288947.56508505],
       [ 658885.90488714],
       [ 719428.54058311],
       [ 391931.6290197 ],
       [ 548527.52954284],
       [ 476768.57161094],
       [ 785200.73988553],
       [ 877287.45689662],
       [ 409439.905208  ],
       [ 700012.61294407],
       [ 342979.64240671],
       [ 635244.63664839],
       [ 593656.93317225],
       [ 609777.3223438 ],
       [ 663553.9673803 ],
       [ 333548.51292975],
       [ 537901.07347094],
       [ 297345.65802685],
       [ 385664.88488711],
       [ 704781.30880107],
       [ 461100.14431273],
       [ 394712.06978255],
       [1189563.43410346],
       [ 340034.58657733],
       [ 576264.17325338],
       [ 907059.81173199],
       [ 386381.01259613],
       [ 318713.3304399 ],
       [ 311258.83139432],
       [ 353753.5625674 ],
       [ 646768.74147554],
       [ 447690.86687803],
       [ 419259.59405244],
       [ 709011.40649979],
       [ 334092.72141495],
       [ 252526.73892472],
       [ 562500.88050969],
       [ 335223.62905442],
       [ 391258.27517307],
       [ 612696.49275261],
       [ 399961.76576523],
       [ 362127.03276162],
       [ 449288.30487547],
       [ 596434.74309924],
       [ 473191.98406789],
       [ 327729.55672889],
       [ 327240.02726075],
       [ 296017.79927167],
       [ 184486.40230339],
       [ 435061.48328742],
       [ 721215.81927893],
       [ 670255.89315864],
       [ 483098.4335707 ],
       [ 445009.51775451],
       [ 273510.50335456],
       [ 396035.71132526],
       [ 309896.38046746],
       [ 702883.76575765],
       [ 750134.15006107],
       [ 520831.86295572],
       [ 442189.37019041],
       [ 267150.29042856],
       [ 492524.61308067],
       [ 621776.9101006 ],
       [ 449943.59225978],
       [ 947994.16217678],
       [ 251207.93919021],
       [ 310687.16426679],
       [ 437529.8262881 ],
       [ 272410.51103055],
       [ 864912.43219831],
       [ 240063.7956215 ],
       [ 474563.04490402],
       [ 846147.99716197],
       [ 456640.70905713],
       [ 762932.19188585],
       [ 788081.30589999],
       [ 583243.12263879],
       [ 456600.1492643 ],
       [ 515471.9625742 ],
       [1150874.22970047],
       [ 418419.13207499],
       [ 329038.50030586],
       [ 629198.33141422],
       [ 342358.85364561],
       [ 402181.40400986],
       [ 500501.00913946],
       [ 338980.20533747],
       [ 696952.30166984],
       [ 425082.85725015],
       [ 397411.35044675],
       [ 481232.98190448],
       [ 285611.50507521],
       [ 574693.8926685 ],
       [1064603.53552918],
       [ 857183.89280864],
       [ 328352.46081787],
       [ 389497.12230034],
       [ 248244.06198699],
       [ 587981.45120841],
       [ 414563.06056248],
       [ 618061.84739236],
       [ 675535.02148249],
       [ 702215.2150962 ],
       [ 682569.25276207],
       [ 555582.68297682],
       [ 326461.66141394],
       [ 434437.54420771],
       [ 298355.02454287],
       [ 370831.51472237],
       [ 211903.54405714],
       [1084637.04219724],
       [ 426614.53771501],
       [ 502053.64413988],
       [ 736556.9926422 ],
       [ 211232.26723312],
       [ 472046.61535693],
       [ 873276.71723078],
       [ 486511.96915616],
       [ 267031.49837781],
       [ 442139.19782878],
       [ 270117.52150777],
       [ 561750.46914301],
       [ 425095.67075668],
       [ 500707.75550618],
       [ 475280.14641745],
       [ 396874.67325483],
       [ 491383.60812256],
       [ 216917.91772106],
       [ 501162.50139941],
       [ 633858.93091562],
       [ 486174.56093551],
       [ 999818.49030511],
       [ 472919.74391331],
       [ 555670.07938005],
       [ 327871.02078552],
       [ 371059.64647086],
       [ 471828.38275435],
       [ 605136.56756626],
       [ 400726.90235453],
       [ 623001.79900671],
       [ 531199.3030877 ],
       [ 613562.13343597],
       [ 895311.93601119],
       [1080107.15133614],
       [ 429480.3043281 ],
       [ 561493.13232136],
       [ 700611.74350244],
       [ 765331.01906379],
       [1164459.33082775],
       [ 504608.48894174],
       [ 715585.45232237],
       [ 520277.45729701],
       [ 275991.3850575 ],
       [ 448204.10401549],
       [ 453392.28764496],
       [ 956804.59620967],
       [ 530405.83962233],
       [ 484833.00076223],
       [ 234080.29392427],
       [ 256368.59400559],
       [1545635.36565822],
       [ 585819.17246964],
       [ 270510.42996035],
       [1087529.78066875],
       [ 875413.81319386],
       [ 575396.49473101],
       [ 713411.52216939],
       [ 408137.36050328],
       [ 485262.37638337],
       [ 505928.27561261],
       [ 748778.36816391],
       [ 498040.14850804],
       [ 591188.99735512],
       [ 351117.52132582],
       [1103102.36129337],
       [ 263710.77822948],
       [ 549932.97892731],
       [ 406616.4758217 ],
       [ 446576.17297472],
       [ 617285.505855  ],
       [ 305186.04974779],
       [ 546360.45607866],
       [ 498687.1548244 ],
       [ 567935.40156895],
       [ 450646.02808942],
       [ 483638.95099393],
       [ 410539.14100991],
       [ 692030.23452935],
       [ 728273.98341072],
       [ 334432.61581772],
       [ 415049.54254475],
       [ 344287.26883907],
       [1221255.31165463],
       [ 277008.14459354],
       [ 923449.72862451],
       [ 454750.29043047],
       [ 595471.85062416],
       [ 327063.5819393 ],
       [ 353604.02458069],
       [ 229366.82478472],
       [ 185292.99888512],
       [ 291198.76052241],
       [ 476297.99174306],
       [ 331475.13398677],
       [ 463242.78911883],
       [ 558779.53638601],
       [ 503531.65884284],
       [ 324094.66718917],
       [ 323994.45684932],
       [ 655083.95653519],
       [ 600519.66548165],
       [ 594317.64488469],
       [ 371570.61331524],
       [ 306998.0758529 ],
       [ 289439.09621918],
       [ 537005.67368615],
       [ 535685.02850993],
       [ 164417.902296  ],
       [ 740679.35692242],
       [ 663136.86720172],
       [ 768125.8402437 ],
       [ 490102.07563392],
       [ 899155.58380934],
       [ 247926.04959815],
       [ 659322.82296551],
       [1054922.7769161 ],
       [ 454489.75574326],
       [ 555677.26616725],
       [ 672025.711626  ],
       [ 560061.07460488],
       [ 530027.58751343],
       [ 489541.32402134],
       [ 763925.08259581],
       [ 489680.52212599],
       [ 552547.78133393],
       [ 414611.72120049],
       [ 329648.36508246],
       [ 333135.07440603],
       [ 597201.70008429],
       [ 518569.61483612],
       [ 256254.2245134 ],
       [ 242444.18249851],
       [ 511658.55693404],
       [ 643203.20695946],
       [ 500959.10922181],
       [ 317547.15082796],
       [ 442552.17564127],
       [ 528849.46846059],
       [ 385159.77681991],
       [ 274607.72884043],
       [ 472155.21528669],
       [1522550.92745593],
       [ 378927.1879945 ],
       [1800767.73990539],
       [ 519295.79950867],
       [ 671381.92720852],
       [ 552051.91912533],
       [ 561224.66992063],
       [ 335530.13348959],
       [ 706532.10142748],
       [ 332240.11167265],
       [ 237077.42888712],
       [ 255652.76693099],
       [ 549499.50904668],
       [ 557246.3539179 ],
       [ 457381.67723675],
       [ 550484.18497828],
       [ 396447.94485985],
       [ 722662.1702766 ],
       [ 269628.71839953],
       [ 821164.62744749],
       [ 692043.60763453],
       [ 804441.73282608],
       [ 789943.16095326],
       [ 715268.73390371],
       [ 664188.74736319],
       [ 552815.41379309],
       [ 505202.25092096],
       [ 419653.24332064],
       [ 375627.86408673],
       [ 278350.26519438],
       [ 324101.53995853],
       [ 749432.9432316 ],
       [ 770141.07720397],
       [ 351741.98408469],
       [ 455305.62787736],
       [ 341797.11060343],
       [ 550475.31724195],
       [ 932287.90782689],
       [1219518.09028415],
       [ 581481.69452367],
       [ 528733.26785779],
       [ 303450.37800664],
       [ 459082.50134151],
       [ 337092.00757988],
       [ 763312.78513257],
       [ 388845.94687811],
       [ 559755.40765103],
       [ 255864.45694888],
       [ 636611.21459142],
       [ 598567.09097139],
       [ 646068.30892049],
       [ 694681.20611365],
       [ 347612.54021636],
       [ 240395.45918002],
       [ 396735.69323257],
       [ 744804.40538594],
       [ 795972.53045   ],
       [ 229781.79814302],
       [ 594307.28665295],
       [ 463526.39997221],
       [ 408108.86353122],
       [ 516320.31730061],
       [ 384022.24760766],
       [1395820.32762381],
       [ 959152.76021294],
       [ 320685.14883968],
       [ 338898.91312302],
       [ 967797.71517622],
       [ 301878.43741801],
       [ 700205.02666039],
       [ 756602.28957392],
       [ 681815.17405011],
       [  91995.87979045],
       [ 777091.9145658 ],
       [1287900.14406383],
       [ 264768.2936627 ],
       [ 712700.91530854],
       [ 647982.97805939],
       [ 451021.21311319],
       [ 217347.4797572 ],
       [ 986283.263201  ],
       [ 264664.91041417],
       [ 369935.150835  ],
       [ 352279.98789943],
       [ 682836.94441207],
       [ 501996.89758964],
       [ 823965.31752689],
       [ 605855.92738988],
       [ 564921.04100403],
       [ 718480.80953955],
       [ 333320.29583412],
       [ 470150.05630043],
       [ 556198.57598481],
       [ 495762.56471742],
       [ 564492.51946981],
       [ 464227.16556807],
       [ 517742.58363888],
       [ 426875.12965504],
       [ 716972.43884397],
       [ 765785.69415586],
       [ 421849.12049111],
       [ 655217.31663489],
       [ 314714.88960822],
       [ 601705.98956359],
       [ 154157.51806949],
       [ 524473.41780809],
       [ 367163.64656707],
       [ 770502.93973139],
       [ 353001.17071427],
       [ 302065.69933849],
       [ 590829.5825069 ],
       [ 730565.22714188],
       [ 322574.49064945],
       [ 597022.06197383],
       [ 356216.31283954],
       [ 518737.15300658],
       [ 425310.88767921],
       [ 916724.39525997],
       [ 740064.93297771],
       [ 276280.03838095],
       [ 364845.02168869],
       [ 774348.34010886],
       [ 410283.25007373],
       [ 972530.86417784],
       [ 757908.68305292],
       [ 390091.12898261],
       [ 455978.26153482],
       [ 479315.88411044],
       [ 850705.45460699],
       [ 547911.18445667],
       [ 563111.03944896],
       [ 214279.89756063],
       [ 370520.78092334],
       [ 545390.03026712],
       [ 907549.44938767],
       [ 796886.93755339],
       [ 486388.05412024],
       [ 410239.56026151],
       [ 551764.91053309],
       [ 292187.83107124],
       [ 671641.56530245],
       [ 845709.88403937],
       [ 466331.30495282],
       [ 893211.52331572],
       [ 668016.95530196],
       [ 631685.31904542],
       [ 474157.75508839],
       [1104374.20150123],
       [1059420.96645852],
       [ 393182.38616429],
       [ 280971.78529791],
       [ 379929.01964427],
       [ 346227.39069635],
       [ 896237.89046507],
       [ 409715.76179552],
       [ 404432.35482548],
       [ 827612.30786979],
       [ 559444.15251479],
       [ 220952.93814348],
       [ 389613.66295616],
       [ 778360.12865977],
       [ 696792.85117872],
       [ 383298.86206775],
       [ 595826.29370903],
       [ 577438.615051  ],
       [ 432022.61767478],
       [ 669268.20098578],
       [ 880019.71735389],
       [ 293160.29223712],
       [ 312876.29986958],
       [ 305621.69393719],
       [ 477461.52136363],
       [ 913507.96928832],
       [ 624804.93971596],
       [ 598939.9151435 ],
       [ 478297.06075345],
       [ 668019.36534074],
       [ 515481.6476287 ],
       [ 940388.98467971],
       [ 583267.02886573],
       [ 358621.13419741],
       [ 767893.99605253],
       [ 311327.16295526],
       [ 494970.62942575],
       [ 407577.74889534],
       [ 504361.17689413],
       [ 637039.59280055],
       [ 795632.92321226],
       [ 418006.75585965],
       [ 581815.63426878],
       [ 516623.54505379],
       [ 474315.88058468],
       [ 441101.01194152],
       [ 861010.74333589],
       [ 291356.81332266],
       [ 725063.70866743],
       [1095295.43140735],
       [ 302479.45730799],
       [ 770492.91219556],
       [ 255384.3882547 ],
       [ 519231.66910512],
       [ 543352.24152716],
       [ 482311.46693944],
       [ 827544.23841929],
       [ 498663.31480416],
       [ 421785.71179399],
       [ 525723.13172369],
       [ 221845.97266791],
       [ 926908.39665986],
       [ 725254.61198267],
       [ 684640.20881926],
       [1054165.98082211],
       [1028954.0866586 ],
       [ 675162.42380653],
       [ 524774.90514301],
       [ 412044.13642629],
       [ 447851.51912346],
       [ 529387.9179569 ],
       [ 319601.19108526],
       [ 604611.37152825],
       [ 756686.11235218],
       [ 428569.72869963],
       [ 504862.11887352],
       [ 484065.53294612],
       [ 664794.65726841],
       [ 238663.17490482],
       [ 659822.67290642],
       [ 263263.123531  ],
       [ 588129.47328774],
       [ 937715.4283522 ],
       [ 527986.92994544],
       [ 305011.34633072],
       [ 587070.87567588],
       [ 289271.09118013],
       [ 649694.47421271],
       [ 527424.68742698],
       [ 302277.64299154],
       [ 478735.83791945],
       [ 293315.33825905],
       [ 335940.50945013],
       [ 347126.14494635],
       [ 259544.98746041],
       [ 303680.23389138],
       [1483876.66072842],
       [ 300700.31053346],
       [ 586399.54328874],
       [ 544465.69712378],
       [ 259521.6168167 ],
       [1116277.98748852],
       [ 407957.64353698],
       [ 563033.18554944],
       [ 545110.57909957],
       [ 543260.38915949],
       [ 579916.42432018],
       [ 611870.76173363],
       [ 736919.22308994],
       [ 344923.77865104],
       [ 488717.74236288],
       [ 676356.16406927],
       [ 492272.32984382],
       [ 400502.55910834],
       [ 565819.65373811],
       [ 825498.46303302],
       [ 509802.97244004],
       [ 747474.22708715],
       [ 716472.58266469],
       [ 751718.69867142],
       [ 610742.00114517],
       [ 865561.99085536],
       [ 829988.56442036],
       [ 550975.13725741],
       [1495246.61913569],
       [ 365571.60240281],
       [ 920432.67841735],
       [ 711372.03513708],
       [ 590094.34264273],
       [ 712316.32408089],
       [ 341665.41947499],
       [ 460930.62291432],
       [ 408292.24284579],
       [ 848648.82323935],
       [ 575263.29369438],
       [ 437241.34609118],
       [1052568.66318566],
       [ 439208.77802081],
       [ 577671.09648799],
       [ 626043.16098628],
       [ 465379.6681295 ],
       [ 314973.28515302],
       [ 680354.35468752],
       [ 618896.38313134],
       [ 297697.83627039],
       [1145036.34408432],
       [1339204.193354  ],
       [ 486072.18386819],
       [ 433685.55900177],
       [ 410537.30125589],
       [1254013.78307169],
       [ 427038.99360121],
       [ 534873.5404903 ],
       [ 750852.5484861 ],
       [ 308754.07438074],
       [ 372934.44676332],
       [ 287368.6143579 ],
       [ 504226.67320126],
       [ 426989.89452283],
       [ 495670.9333062 ],
       [ 610255.43130177],
       [ 558590.71284485],
       [ 417059.14199014],
       [ 443612.85304197],
       [ 535553.56045149],
       [ 459385.44663594],
       [ 292424.26721909],
       [ 354046.42035246],
       [ 520283.23518041],
       [ 416108.58890688],
       [ 639436.3836977 ],
       [ 710969.55082115],
       [ 443734.29989587],
       [1652861.55129173],
       [ 591935.31690007],
       [ 347656.70435176],
       [ 642340.43540081],
       [ 567856.05324609],
       [ 331966.27119903],
       [ 526138.21374649],
       [ 764573.43855499],
       [ 697427.02110077],
       [ 444591.59500037],
       [ 541949.77284105],
       [ 308702.41932882],
       [ 609247.60824268],
       [ 463401.22330935],
       [ 660871.45796739],
       [ 354724.67984561],
       [ 326969.41308296],
       [ 167531.93331295],
       [ 616274.90642748],
       [ 388153.62012883],
       [ 334849.64180729],
       [1251978.23325964],
       [ 677845.5405137 ],
       [ 679690.46974069],
       [ 775807.14120258],
       [ 342147.55462647],
       [ 197227.26359526],
       [ 520655.56481487],
       [ 677919.9669253 ],
       [ 502946.76305107],
       [ 610550.94659785],
       [ 330709.64024737],
       [ 849327.11717018],
       [ 781734.08028893],
       [ 505279.78099409],
       [ 617204.14163402],
       [ 613348.50832207],
       [ 360937.60673204],
       [ 393916.62784089],
       [ 512043.25281763],
       [ 181109.91359826],
       [ 566376.03274179],
       [ 300604.27904814],
       [ 316965.79720351],
       [ 512160.25907148],
       [1121408.96868435],
       [ 481806.0363436 ],
       [ 546274.9603663 ],
       [ 336082.28528003],
       [ 520253.50693569],
       [ 513884.61022922],
       [1278736.47178555],
       [ 234803.23993259],
       [ 491943.91263295],
       [ 381652.66949898],
       [ 795782.08827871],
       [ 213555.70792275],
       [ 445309.13270145],
       [ 219772.04948718],
       [ 399386.48616595],
       [ 372242.38220762],
       [ 399074.92599478],
       [ 282800.33116527],
       [ 845886.26398442],
       [ 409406.5954877 ],
       [ 567159.45087031],
       [ 255668.22543689],
       [ 201343.635813  ],
       [ 275702.09867113],
       [ 466252.97170232],
       [ 533094.76915949],
       [ 439228.37029164],
       [ 310199.48226952],
       [ 471378.59455072],
       [ 509644.8913902 ],
       [ 455647.05690812],
       [ 689243.2638108 ],
       [ 305013.89755378],
       [ 745230.22683999],
       [ 513493.15834985],
       [ 524866.24705624],
       [ 378021.05334392],
       [ 864143.2235368 ],
       [ 403499.56445064],
       [ 336334.33207416],
       [ 413507.93739938],
       [ 662065.39036666],
       [ 683071.68045527],
       [ 894898.09650185],
       [ 878921.92102471],
       [ 381328.45587414],
       [ 704548.41858602],
       [ 219657.86953118],
       [ 401046.64180875],
       [ 360822.66612682],
       [ 228889.38144246],
       [ 582804.83572764],
       [ 225956.37288192],
       [ 304969.99325475],
       [ 335287.14034407],
       [ 374439.69287226],
       [ 556949.50375953],
       [ 390686.1717465 ],
       [ 996089.84629151],
       [ 716719.2662578 ],
       [ 931393.18921483],

In [ ]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [ ]:
mean_absolute_error(y_test,y_pred)

163393.08902736125

In [ ]:
mean_squared_error(y_test,y_pred)

65434374374.42693

In [ ]:
r2_score(y_test,y_pred)

0.4235370347208216